# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_win.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 627)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.study = QtWidgets.QWidget()
        self.study.setObjectName("study")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.study)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.problem = QtWidgets.QLabel(self.study)
        self.problem.setWordWrap(True)
        self.problem.setObjectName("problem")
        self.gridLayout_2.addWidget(self.problem, 0, 0, 1, 4)
        self.remark = QtWidgets.QLabel(self.study)
        self.remark.setText("")
        self.remark.setAlignment(QtCore.Qt.AlignCenter)
        self.remark.setObjectName("remark")
        self.gridLayout_2.addWidget(self.remark, 4, 0, 1, 4)
        self.solution = QtWidgets.QLineEdit(self.study)
        self.solution.setObjectName("solution")
        self.gridLayout_2.addWidget(self.solution, 1, 1, 1, 1)
        self.task = QtWidgets.QLabel(self.study)
        self.task.setObjectName("task")
        self.gridLayout_2.addWidget(self.task, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 401, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
        self.verify = QtWidgets.QPushButton(self.study)
        self.verify.setDefault(True)
        self.verify.setFlat(False)
        self.verify.setObjectName("verify")
        self.gridLayout_2.addWidget(self.verify, 1, 2, 1, 1)
        self.skip = QtWidgets.QPushButton(self.study)
        self.skip.setObjectName("skip")
        self.gridLayout_2.addWidget(self.skip, 1, 3, 1, 1)
        self.ver = QtWidgets.QLabel(self.study)
        self.ver.setObjectName("ver")
        self.gridLayout_2.addWidget(self.ver, 6, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        self.tabWidget.addTab(self.study, "")
        self.statistic = QtWidgets.QWidget()
        self.statistic.setObjectName("statistic")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.statistic)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableUser = QtWidgets.QTableWidget(self.statistic)
        self.tableUser.setObjectName("tableUser")
        self.tableUser.setColumnCount(5)
        self.tableUser.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableUser.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableUser.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableUser.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableUser.setItem(0, 4, item)
        self.gridLayout_4.addWidget(self.tableUser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.statistic, "")
        self.preferences = QtWidgets.QWidget()
        self.preferences.setObjectName("preferences")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.preferences)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 4, 0, 1, 1)
        self.checkBox_droby = QtWidgets.QCheckBox(self.preferences)
        self.checkBox_droby.setObjectName("checkBox_droby")
        self.gridLayout_3.addWidget(self.checkBox_droby, 3, 0, 1, 1)
        self.radioButton_all_syst = QtWidgets.QRadioButton(self.preferences)
        self.radioButton_all_syst.setObjectName("radioButton_all_syst")
        self.gridLayout_3.addWidget(self.radioButton_all_syst, 2, 0, 1, 1)
        self.radioButton_2_4_8 = QtWidgets.QRadioButton(self.preferences)
        self.radioButton_2_4_8.setObjectName("radioButton_2_4_8")
        self.gridLayout_3.addWidget(self.radioButton_2_4_8, 1, 0, 1, 1)
        self.radioButton_bin_only = QtWidgets.QRadioButton(self.preferences)
        self.radioButton_bin_only.setChecked(True)
        self.radioButton_bin_only.setObjectName("radioButton_bin_only")
        self.gridLayout_3.addWidget(self.radioButton_bin_only, 0, 0, 1, 1)
        self.tabWidget.addTab(self.preferences, "")
        self.teacher = QtWidgets.QWidget()
        self.teacher.setObjectName("teacher")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.teacher)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_export_stat = QtWidgets.QPushButton(self.teacher)
        self.pushButton_export_stat.setObjectName("pushButton_export_stat")
        self.gridLayout_5.addWidget(self.pushButton_export_stat, 1, 1, 1, 1)
        self.pushButton_new_user = QtWidgets.QPushButton(self.teacher)
        self.pushButton_new_user.setObjectName("pushButton_new_user")
        self.gridLayout_5.addWidget(self.pushButton_new_user, 1, 0, 1, 1)
        self.pushButton_clear_stat = QtWidgets.QPushButton(self.teacher)
        self.pushButton_clear_stat.setObjectName("pushButton_clear_stat")
        self.gridLayout_5.addWidget(self.pushButton_clear_stat, 1, 2, 1, 1)
        self.tableAllUser = QtWidgets.QTableWidget(self.teacher)
        self.tableAllUser.setObjectName("tableAllUser")
        self.tableAllUser.setColumnCount(5)
        self.tableAllUser.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUser.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUser.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUser.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUser.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUser.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUser.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllUser.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableAllUser.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableAllUser.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableAllUser.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableAllUser.setItem(0, 4, item)
        self.gridLayout_5.addWidget(self.tableAllUser, 0, 0, 1, 3)
        self.tabWidget.addTab(self.teacher, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.solution)
        MainWindow.setTabOrder(self.solution, self.verify)
        MainWindow.setTabOrder(self.verify, self.skip)
        MainWindow.setTabOrder(self.skip, self.tableUser)
        MainWindow.setTabOrder(self.tableUser, self.radioButton_bin_only)
        MainWindow.setTabOrder(self.radioButton_bin_only, self.radioButton_2_4_8)
        MainWindow.setTabOrder(self.radioButton_2_4_8, self.radioButton_all_syst)
        MainWindow.setTabOrder(self.radioButton_all_syst, self.checkBox_droby)
        MainWindow.setTabOrder(self.checkBox_droby, self.tableAllUser)
        MainWindow.setTabOrder(self.tableAllUser, self.pushButton_new_user)
        MainWindow.setTabOrder(self.pushButton_new_user, self.pushButton_export_stat)
        MainWindow.setTabOrder(self.pushButton_export_stat, self.pushButton_clear_stat)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Изучаем системы счисления. V 1.2"))
        self.problem.setText(_translate("MainWindow", "Введите значение числа"))
        self.task.setText(_translate("MainWindow", "1"))
        self.verify.setText(_translate("MainWindow", "Проверить"))
        self.skip.setText(_translate("MainWindow", "Следующее число"))
        self.ver.setText(_translate("MainWindow", "Статистика выполнения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.study), _translate("MainWindow", "Обучение"))
        item = self.tableUser.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableUser.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableUser.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableUser.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Пользователь"))
        item = self.tableUser.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.tableUser.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Уровень"))
        item = self.tableUser.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Попыток"))
        item = self.tableUser.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Успешно"))
        __sortingEnabled = self.tableUser.isSortingEnabled()
        self.tableUser.setSortingEnabled(False)
        item = self.tableUser.item(0, 0)
        item.setText(_translate("MainWindow", "01.01.2021"))
        item = self.tableUser.item(0, 1)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableUser.item(0, 3)
        item.setText(_translate("MainWindow", "77"))
        item = self.tableUser.item(0, 4)
        item.setText(_translate("MainWindow", "3"))
        self.tableUser.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statistic), _translate("MainWindow", "Статистика"))
        self.checkBox_droby.setText(_translate("MainWindow", "Использовать дробные числа"))
        self.radioButton_all_syst.setText(_translate("MainWindow", "2-, 4-, 8-, 16-ричные системы счисления"))
        self.radioButton_2_4_8.setText(_translate("MainWindow", "Двоичная, четверичная, восьмеричная системы счисления"))
        self.radioButton_bin_only.setText(_translate("MainWindow", "Только двоичная система счисления"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preferences), _translate("MainWindow", "Настройка"))
        self.pushButton_export_stat.setText(_translate("MainWindow", "Выгрузить статистику"))
        self.pushButton_new_user.setText(_translate("MainWindow", "Добавить ученика"))
        self.pushButton_clear_stat.setText(_translate("MainWindow", "Очистить статистику"))
        item = self.tableAllUser.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableAllUser.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableAllUser.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableAllUser.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Учащийся"))
        item = self.tableAllUser.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.tableAllUser.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Уровень"))
        item = self.tableAllUser.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Попыток"))
        item = self.tableAllUser.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Успешно"))
        __sortingEnabled = self.tableAllUser.isSortingEnabled()
        self.tableAllUser.setSortingEnabled(False)
        item = self.tableAllUser.item(0, 0)
        item.setText(_translate("MainWindow", "01.01.2021"))
        item = self.tableAllUser.item(0, 2)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableAllUser.item(0, 3)
        item.setText(_translate("MainWindow", "77"))
        item = self.tableAllUser.item(0, 4)
        item.setText(_translate("MainWindow", "3"))
        self.tableAllUser.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.teacher), _translate("MainWindow", "Учителю"))
        self.action_2.setText(_translate("MainWindow", "За сегодня"))
        self.action_3.setText(_translate("MainWindow", "За все время"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

