# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_win.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 627)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.study = QtWidgets.QWidget()
        self.study.setObjectName("study")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.study)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.solution = QtWidgets.QLineEdit(self.study)
        self.solution.setObjectName("solution")
        self.gridLayout_2.addWidget(self.solution, 1, 1, 1, 1)
        self.verify = QtWidgets.QPushButton(self.study)
        self.verify.setDefault(True)
        self.verify.setFlat(False)
        self.verify.setObjectName("verify")
        self.gridLayout_2.addWidget(self.verify, 1, 2, 1, 1)
        self.ver = QtWidgets.QLabel(self.study)
        self.ver.setObjectName("ver")
        self.gridLayout_2.addWidget(self.ver, 3, 0, 1, 4)
        self.task = QtWidgets.QLabel(self.study)
        self.task.setObjectName("task")
        self.gridLayout_2.addWidget(self.task, 1, 0, 1, 1)
        self.skip = QtWidgets.QPushButton(self.study)
        self.skip.setObjectName("skip")
        self.gridLayout_2.addWidget(self.skip, 1, 3, 1, 1)
        self.problem = QtWidgets.QLabel(self.study)
        self.problem.setWordWrap(True)
        self.problem.setObjectName("problem")
        self.gridLayout_2.addWidget(self.problem, 0, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(20, 401, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.remark = QtWidgets.QLabel(self.study)
        self.remark.setText("")
        self.remark.setObjectName("remark")
        self.gridLayout_2.addWidget(self.remark, 2, 0, 1, 4)
        self.tabWidget.addTab(self.study, "")
        self.statistic = QtWidgets.QWidget()
        self.statistic.setObjectName("statistic")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.statistic)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.statistic)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget.setItem(0, 3, item)
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.statistic, "")
        self.preferences = QtWidgets.QWidget()
        self.preferences.setObjectName("preferences")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.preferences)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.preferences)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_3.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.preferences)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.preferences)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 1)
        self.tabWidget.addTab(self.preferences, "")
        self.teacher = QtWidgets.QWidget()
        self.teacher.setObjectName("teacher")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.teacher)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.teacher)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setItem(0, 4, item)
        self.gridLayout_5.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.teacher, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Изучаем системы счисления. V 1.2"))
        self.verify.setText(_translate("MainWindow", "Проверить"))
        self.ver.setText(_translate("MainWindow", "Статистика выполнения"))
        self.task.setText(_translate("MainWindow", "1"))
        self.skip.setText(_translate("MainWindow", "Следующее число"))
        self.problem.setText(_translate("MainWindow", "Введите значение числа"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.study), _translate("MainWindow", "Обучение"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Новая строка"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Новая строка"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Новая строка"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Заданий"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Попыток"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Успешно"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "01.01.2021"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "77"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "3"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statistic), _translate("MainWindow", "Статистика"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preferences), _translate("MainWindow", "Настройка"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Новая строка"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Новая строка"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Новая строка"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Учащийся"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Заданий"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Попыток"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Успешно"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("MainWindow", "01.01.2021"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("MainWindow", "77"))
        item = self.tableWidget_2.item(0, 4)
        item.setText(_translate("MainWindow", "3"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.teacher), _translate("MainWindow", "Учителю"))
        self.action_2.setText(_translate("MainWindow", "За сегодня"))
        self.action_3.setText(_translate("MainWindow", "За все время"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

